### ISSUE TITLE
Docker 运行问题

### ISSUE THREAD

**Issue by zhongjixiuxing** [jinmu333/python_PlateRecogntion#30]
### 操作过程
Hi, 我根据你的 readme.md 操作，用 `docker-compose up -d` 将实例运行起来后，然后进入到 docker container 实例里面执行 `python3 main.py`, 就遇到下面的错误 
`
Traceback (most recent call last):
  File "main.py", line 538, in <module>
    win = tk.Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0.0"
`

这个需要怎样解决？我对 python 不熟悉，麻烦你看下吖。

### 运行环境 
- 系统： macos(M1)

**Comment by jinmu333** [comment]
你好，M1 mac 暂未测试
我之后验证一下
请问是 master 分支吗

**Comment by jinmu333** [comment]
<img width="1632" alt="image" src="https://user-images.githubusercontent.com/32295532/163671757-32af87d6-8d78-431f-8373-43803f5cab34.png">
我写的不太清楚，需要打开远程桌面的终端来运行

**Comment by zhongjixiuxing** [comment]
> 你好，M1 mac 暂未测试 我之后验证一下 请问是 master 分支吗

master 分支.

UP 主有没考虑不需要命令，只在后台批处理的情况？

你用的是什么系统来运行的？

**Comment by jinmu333** [comment]
exec 到容器之后先 执行 `export DISPLAY=:1`，
然后执行 `python3 login.py ` 即可

**Comment by jinmu333** [comment]
> > 你好，M1 mac 暂未测试 我之后验证一下 请问是 master 分支吗
> 
> master 分支.
> 
> UP 主有没考虑不需要命令，只在后台批处理的情况？
> 
> 你用的是什么系统来运行的？

M1 已测试，最新代码已测试，按照 readme 即可
