### ISSUE TITLE
需求讨论: 将识别的车牌替换

### ISSUE THREAD

**Issue by zhongjixiuxing** [jinmu333/python_PlateRecogntion#31]
不知能不能实现一个 img 工具函数，将图片中识别到的车牌用另一张车牌 logo 按照比例覆盖替换它？

**Comment by zhongjixiuxing** [comment]
例如像这样的效果

![image](https://user-images.githubusercontent.com/8935235/163674811-b91f13bc-84e4-4252-bc44-aa228eaf332d.png)

**Comment by zhongjixiuxing** [comment]
参考资料： https://stackoverflow.com/questions/57262520/replacing-a-solid-green-region-with-another-image-with-opencv

**Comment by zhongjixiuxing** [comment]
> 参考资料： https://stackoverflow.com/questions/57262520/replacing-a-solid-green-region-with-another-image-with-opencv

@jinmu333 不知最近你是否有时间增加下这个功能

**Comment by jinmu333** [comment]
> > 参考资料： https://stackoverflow.com/questions/57262520/replacing-a-solid-green-region-with-another-image-with-opencv
> 
> @jinmu333 不知最近你是否有时间增加下这个功能

是将识别到的车牌区域换成一张自己生成的图片是吗

**Comment by zhongjixiuxing** [comment]
> > > 参考资料： https://stackoverflow.com/questions/57262520/replacing-a-solid-green-region-with-another-image-with-opencv
> > 
> > 
> > @jinmu333 不知最近你是否有时间增加下这个功能
> 
> 是将识别到的车牌区域换成一张自己生成的图片是吗

嗯嗯
