### ISSUE TITLE
Can cigarette bar code recognition be done like license plate recognition？

### ISSUE THREAD

**Issue by renjiechao88** [jinmu333/python_PlateRecogntion#4]
Can cigarette bar code recognition be done like license plate recognition？Because background is blue  in license plate recognition，cigarette is different。
Thank you for your reply。

**Comment by jinmu333** [comment]
![image](https://user-images.githubusercontent.com/32295532/75890717-b6393180-5e69-11ea-883a-5a60480847d0.png)

like this?
